title: Paul's Blog
email: pgigioli@alumni.nd.edu
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pgigioli

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "_posts/projects"
    values:
        layout: "post"
        categories: project
  -
    scope:
      path: "_post/blog"
    values:
        layout: "post"
        categories: blog
